language: cpp
sudo: false
dist: trusty

os:
- linux

env:
  global:
    secure: zvMqm4o5LizORd+Jzt43fLtx94CUxDa/RbGKg6xJiii7EbOTtV46xdSAQ5HiKXJwfDHm8a5+Kj8JWO069RxcHkfpcvzffALYncXQlz+kOq+9MZ5SBn3Wvm0r3QFaankxc+GDJxtWzQXVEee/HGOEbLCITzDiJrllS/24qOeP9mRYlRD8OZVkJgPNs8deW/gCa9WK0dlHXHOH2Lx1KOvpjqerdVPEyAh31iqdr8/HyhMyYzn1/6C5nvGYoB0WLuZFy/6yUbtB+6CbBC1ezdCUxFwI5QuN1pw1an1BZuv+Na8R5fg8V2i/p3GGlrHsF/Z7WUYwuD0G8oW1x9kwrZUTBcCtKWpI0zDMUQkUITti0I2fAP36qRWBv4fVJ+uhvF6AnqblvHeqPtjte0jOFSgsiDEFxtib+N8PUZJnUKCqP7fFO76SSV+nOVhKSGe8LAsc9cxYONfHnxlkkRItUmHMkmajVtF7Stm/Ofg1uy2JleiqENp+wBC8IfHwHBKcayRcsmcCELr30UfIKAGoYtjIMoccV5y98YorjXry44+XdAfTNjk9J5UdtKFRVfSUznietEAqq/CFgKAwJkDXpQzfVaMRYwkZJu5pj8/aUIfzUegyfzuzBjQMGNARTtjoba2seNcxZHzsSGiL5dwFaFxB+ROuWv1CfNkrap2lLpfUIPA=

script:
- echo "Script"
- echo "SOMEVAR => ${SOMEVAR}"
- sh format-script.sh
